// Shared logic for the skilldeck tooling.
//
// The `skills/` tree is the single source of truth. `generate.mjs` writes the
// derived artifacts (marketplace manifest, registry, README catalog) from it;
// `validate.mjs` rebuilds them in memory and asserts the committed copies match.
// Everything here is deterministic — no timestamps, no ordering by anything but
// name/taxonomy — so the same input always produces byte-identical output.

import { readFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

export const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
export const SKILLS_DIR = join(ROOT, "skills");
// The canonical, human-facing marketplace manifest.
export const MARKETPLACE_PATH = join(ROOT, "plugins", "marketplace.json");
// Compatibility shim: Claude Code's native plugin marketplace hard-codes this
// exact path, so `generate` mirrors the manifest here byte-for-byte. Generated —
// do not edit by hand; edit skills/ and run `npm run generate` instead.
export const CLAUDE_MARKETPLACE_PATH = join(ROOT, ".claude-plugin", "marketplace.json");
export const REGISTRY_PATH = join(ROOT, "registry.json");
export const README_PATH = join(ROOT, "README.md");
export const SCHEMA_PATH = join(ROOT, "schema", "skill.schema.json");

// Category display order in the catalog; also the accepted taxonomy.
export const CATEGORY_ORDER = [
  "coding",
  "writing",
  "research",
  "data",
  "devops",
  "productivity",
  "design",
  "security",
  "meta",
];

const CATEGORY_LABELS = {
  coding: "Coding",
  writing: "Writing",
  research: "Research",
  data: "Data",
  devops: "DevOps",
  productivity: "Productivity",
  design: "Design",
  security: "Security",
  meta: "Meta",
};

export const CATALOG_START =
  "<!-- CATALOG:START (generated by scripts/generate.mjs — do not edit) -->";
export const CATALOG_END = "<!-- CATALOG:END -->";

export function stringifyJson(value) {
  return JSON.stringify(value, null, 2) + "\n";
}

// Minimal YAML frontmatter reader: we only need `name` and whether a
// `description` key is present, so we avoid a YAML dependency.
export function parseFrontmatter(md) {
  const match = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return null;
  const block = match[1];
  const name = (block.match(/^name:\s*(\S+)\s*$/m) || [])[1] ?? null;
  const hasDescription = /^description:\s*/m.test(block);
  return { name, hasDescription };
}

export function listSkillNames() {
  let entries;
  try {
    entries = readdirSync(SKILLS_DIR);
  } catch {
    return [];
  }
  return entries
    .filter((name) => {
      const dir = join(SKILLS_DIR, name);
      return statSync(dir).isDirectory();
    })
    .sort();
}

// Load one skill without throwing; errors are returned for the caller to report.
export function loadSkill(name) {
  const dir = join(SKILLS_DIR, name);
  const relDir = `skills/${name}`;
  const result = {
    name,
    relDir,
    meta: null,
    metaError: null,
    frontmatter: null,
    frontmatterError: null,
  };

  try {
    result.meta = JSON.parse(readFileSync(join(dir, "skill.json"), "utf8"));
  } catch (err) {
    result.metaError = err.code === "ENOENT" ? "skill.json is missing" : `skill.json: ${err.message}`;
  }

  try {
    const md = readFileSync(join(dir, "SKILL.md"), "utf8");
    const fm = parseFrontmatter(md);
    if (!fm) result.frontmatterError = "SKILL.md has no YAML frontmatter";
    else result.frontmatter = fm;
  } catch (err) {
    result.frontmatterError = err.code === "ENOENT" ? "SKILL.md is missing" : `SKILL.md: ${err.message}`;
  }

  return result;
}

export function loadAllSkills() {
  return listSkillNames().map(loadSkill);
}

// Top-level marketplace metadata is preserved from the existing manifest so
// hand-set owner/description survive regeneration; only `plugins` is derived.
export function readMarketplaceBase() {
  const current = JSON.parse(readFileSync(MARKETPLACE_PATH, "utf8"));
  return {
    name: current.name,
    owner: current.owner,
    description: current.description,
    version: current.version,
  };
}

export function buildMarketplace(skills, base) {
  const plugins = skills
    .map((s) => ({
      name: s.meta.name,
      description: s.meta.description,
      version: s.meta.version,
      source: "./",
      strict: false,
      skills: [`./${s.relDir}`],
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  return {
    name: base.name,
    owner: base.owner,
    description: base.description,
    version: base.version,
    plugins,
  };
}

export function buildRegistry(skills) {
  const entries = skills
    .map((s) => {
      const m = s.meta;
      const entry = {
        name: m.name,
        description: m.description,
        category: m.category,
        version: m.version,
        author: m.author,
        license: m.license,
        path: s.relDir,
      };
      if (m.tags) entry.tags = m.tags;
      if (m.homepage) entry.homepage = m.homepage;
      if (m.compatibility) entry.compatibility = m.compatibility;
      return entry;
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  return { name: "skilldeck", skills: entries };
}

export function renderCatalog(skills) {
  const byCategory = new Map();
  for (const s of skills) {
    const cat = s.meta.category;
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push(s);
  }

  const sections = [];
  for (const cat of CATEGORY_ORDER) {
    const group = byCategory.get(cat);
    if (!group || group.length === 0) continue;
    group.sort((a, b) => a.meta.name.localeCompare(b.meta.name));
    const rows = group
      .map((s) => {
        const desc = s.meta.description.replace(/\|/g, "\\|");
        return `| [\`${s.meta.name}\`](${s.relDir}/) | ${desc} |`;
      })
      .join("\n");
    sections.push(`### ${CATEGORY_LABELS[cat]}\n\n| Skill | Description |\n| --- | --- |\n${rows}`);
  }
  return sections.join("\n\n");
}

export function spliceCatalog(readmeText, catalogMd) {
  const start = readmeText.indexOf(CATALOG_START);
  const end = readmeText.indexOf(CATALOG_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `README.md is missing the catalog markers (${CATALOG_START} ... ${CATALOG_END}).`
    );
  }
  const before = readmeText.slice(0, start + CATALOG_START.length);
  const after = readmeText.slice(end);
  return `${before}\n\n${catalogMd}\n\n${after}`;
}
